export const TOGGLE_EBOOK_SELECTION = "TOGGLE_EBOOK_SELECTION";
export const UPDATE_PERSONAL_DATA = "UPDATE_PERSONAL_DATA";
export const UPDATE_BILLING_ADDRESS = "UPDATE_BILLING_ADDRESS";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const BUY = "BUY";
